package com.bj186.oas.mapper;

import com.bj186.oas.pojo.Announcements;

public interface AnnouncementsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_announcements
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int deleteByPrimaryKey(Integer announcementsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_announcements
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insert(Announcements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_announcements
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insertSelective(Announcements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_announcements
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    Announcements selectByPrimaryKey(Integer announcementsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_announcements
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeySelective(Announcements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_announcements
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKey(Announcements record);
}