package com.bj186.oas.mapper;

import com.bj186.oas.pojo.AnnouncementsExtent;

public interface AnnouncementsExtentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_announcementsextent
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int deleteByPrimaryKey(Integer announcementsextentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_announcementsextent
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insert(AnnouncementsExtent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_announcementsextent
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insertSelective(AnnouncementsExtent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_announcementsextent
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    AnnouncementsExtent selectByPrimaryKey(Integer announcementsextentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_announcementsextent
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeySelective(AnnouncementsExtent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_announcementsextent
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKey(AnnouncementsExtent record);
}