package com.bj186.oas.mapper;

import com.bj186.oas.pojo.Calendar;

public interface CalendarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_calendar
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int deleteByPrimaryKey(String calendarId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_calendar
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insert(Calendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_calendar
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insertSelective(Calendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_calendar
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    Calendar selectByPrimaryKey(String calendarId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_calendar
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeySelective(Calendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_calendar
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Calendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_calendar
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKey(Calendar record);
}