package com.bj186.oas.mapper;

import com.bj186.oas.pojo.CheckingIn;

public interface CheckingInMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_checkingin
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int deleteByPrimaryKey(String checkinginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_checkingin
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insert(CheckingIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_checkingin
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insertSelective(CheckingIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_checkingin
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    CheckingIn selectByPrimaryKey(String checkinginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_checkingin
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeySelective(CheckingIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_checkingin
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKey(CheckingIn record);
}