package com.bj186.oas.mapper;

import com.bj186.oas.pojo.Department;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_department
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int deleteByPrimaryKey(Integer depId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_department
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_department
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_department
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    Department selectByPrimaryKey(Integer depId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_department
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeySelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_department
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKey(Department record);
}