package com.bj186.oas.mapper;

import com.bj186.oas.pojo.Files;

public interface FilesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_files
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int deleteByPrimaryKey(Integer filesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_files
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insert(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_files
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insertSelective(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_files
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    Files selectByPrimaryKey(Integer filesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_files
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeySelective(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_files
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKey(Files record);
}