package com.bj186.oas.mapper;

import com.bj186.oas.pojo.Fixed;

public interface FixedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_fixed
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int deleteByPrimaryKey(Integer fixId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_fixed
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insert(Fixed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_fixed
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insertSelective(Fixed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_fixed
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    Fixed selectByPrimaryKey(Integer fixId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_fixed
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeySelective(Fixed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_fixed
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKey(Fixed record);
}