package com.bj186.oas.mapper;

import com.bj186.oas.pojo.Leave;

public interface LeaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_leave
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int deleteByPrimaryKey(String leaveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_leave
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insert(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_leave
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insertSelective(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_leave
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    Leave selectByPrimaryKey(String leaveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_leave
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeySelective(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_leave
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_leave
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKey(Leave record);
}