package com.bj186.oas.mapper;

import com.bj186.oas.pojo.LeaveAdvice;

public interface LeaveAdviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_leaveadvice
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int deleteByPrimaryKey(String leaveadviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_leaveadvice
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insert(LeaveAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_leaveadvice
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insertSelective(LeaveAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_leaveadvice
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    LeaveAdvice selectByPrimaryKey(String leaveadviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_leaveadvice
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeySelective(LeaveAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_leaveadvice
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKey(LeaveAdvice record);
}