package com.bj186.oas.mapper;

import com.bj186.oas.pojo.Meeting;

public interface MeetingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_meeting
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int deleteByPrimaryKey(String meetingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_meeting
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insert(Meeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_meeting
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insertSelective(Meeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_meeting
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    Meeting selectByPrimaryKey(String meetingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_meeting
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeySelective(Meeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_meeting
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Meeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_meeting
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKey(Meeting record);
}