package com.bj186.oas.mapper;

import com.bj186.oas.pojo.MeetingStaff;

public interface MeetingStaffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_meetingstaff
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int deleteByPrimaryKey(String meetingstaffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_meetingstaff
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insert(MeetingStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_meetingstaff
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insertSelective(MeetingStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_meetingstaff
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    MeetingStaff selectByPrimaryKey(String meetingstaffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_meetingstaff
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeySelective(MeetingStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_meetingstaff
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKey(MeetingStaff record);
}