package com.bj186.oas.mapper;

import com.bj186.oas.pojo.Pay;

public interface PayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_pay
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int deleteByPrimaryKey(Integer payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_pay
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insert(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_pay
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insertSelective(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_pay
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    Pay selectByPrimaryKey(Integer payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_pay
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeySelective(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_pay
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKey(Pay record);
}