package com.bj186.oas.mapper;

import com.bj186.oas.pojo.Power;

public interface PowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_power
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int deleteByPrimaryKey(Integer powerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_power
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insert(Power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_power
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insertSelective(Power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_power
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    Power selectByPrimaryKey(Integer powerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_power
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeySelective(Power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_power
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKey(Power record);
}