package com.bj186.oas.mapper;

import com.bj186.oas.pojo.Proof;

public interface ProofMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_proof
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int deleteByPrimaryKey(Integer proofId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_proof
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insert(Proof record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_proof
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insertSelective(Proof record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_proof
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    Proof selectByPrimaryKey(Integer proofId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_proof
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeySelective(Proof record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_proof
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKey(Proof record);
}