package com.bj186.oas.mapper;

import com.bj186.oas.pojo.Reimburse;

public interface ReimburseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_reimburse
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int deleteByPrimaryKey(Integer reimId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_reimburse
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insert(Reimburse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_reimburse
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insertSelective(Reimburse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_reimburse
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    Reimburse selectByPrimaryKey(Integer reimId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_reimburse
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeySelective(Reimburse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_reimburse
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKey(Reimburse record);
}