package com.bj186.oas.mapper;

import com.bj186.oas.pojo.Rent;

public interface RentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_rent
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int deleteByPrimaryKey(Integer rentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_rent
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insert(Rent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_rent
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insertSelective(Rent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_rent
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    Rent selectByPrimaryKey(Integer rentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_rent
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeySelective(Rent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_rent
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKey(Rent record);
}