package com.bj186.oas.mapper;

import com.bj186.oas.pojo.Rule;

public interface RuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_rule
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int deleteByPrimaryKey(Integer ruleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_rule
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insert(Rule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_rule
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insertSelective(Rule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_rule
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    Rule selectByPrimaryKey(Integer ruleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_rule
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeySelective(Rule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_rule
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Rule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_rule
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKey(Rule record);
}