package com.bj186.oas.mapper;

import com.bj186.oas.pojo.StaffPower;

public interface StaffPowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_staffpower
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int deleteByPrimaryKey(Integer spId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_staffpower
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insert(StaffPower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_staffpower
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insertSelective(StaffPower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_staffpower
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    StaffPower selectByPrimaryKey(Integer spId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_staffpower
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeySelective(StaffPower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_staffpower
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKey(StaffPower record);
}