package com.bj186.oas.mapper;

import com.bj186.oas.pojo.StaffDep;

public interface StaffDepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_staffdep
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int deleteByPrimaryKey(Integer sdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_staffdep
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insert(StaffDep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_staffdep
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insertSelective(StaffDep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_staffdep
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    StaffDep selectByPrimaryKey(Integer sdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_staffdep
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeySelective(StaffDep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_staffdep
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKey(StaffDep record);
}