package com.bj186.oas.mapper;

import com.bj186.oas.pojo.Users;

public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_users
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int deleteByPrimaryKey(Integer usersId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_users
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_users
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insertSelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_users
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    Users selectByPrimaryKey(Integer usersId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_users
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeySelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_users
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKey(Users record);
}