package com.bj186.oas.mapper;

import com.bj186.oas.pojo.WorkLog;

public interface WorkLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_worklog
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int deleteByPrimaryKey(Integer worklogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_worklog
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insert(WorkLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_worklog
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int insertSelective(WorkLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_worklog
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    WorkLog selectByPrimaryKey(Integer worklogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_worklog
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeySelective(WorkLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_worklog
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(WorkLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oas_worklog
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    int updateByPrimaryKey(WorkLog record);
}