package com.bj186.oas.pojo;

public class AnnouncementsExtent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_announcementsextent.announcementsExtent_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer announcementsextentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_announcementsextent.announcementsExtent_departmentId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer announcementsextentDepartmentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_announcementsextent.announcementsExtent_announcementsId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer announcementsextentAnnouncementsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_announcementsextent.announcementsExtent_id
     *
     * @return the value of oas_announcementsextent.announcementsExtent_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getAnnouncementsextentId() {
        return announcementsextentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_announcementsextent.announcementsExtent_id
     *
     * @param announcementsextentId the value for oas_announcementsextent.announcementsExtent_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setAnnouncementsextentId(Integer announcementsextentId) {
        this.announcementsextentId = announcementsextentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_announcementsextent.announcementsExtent_departmentId
     *
     * @return the value of oas_announcementsextent.announcementsExtent_departmentId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getAnnouncementsextentDepartmentid() {
        return announcementsextentDepartmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_announcementsextent.announcementsExtent_departmentId
     *
     * @param announcementsextentDepartmentid the value for oas_announcementsextent.announcementsExtent_departmentId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setAnnouncementsextentDepartmentid(Integer announcementsextentDepartmentid) {
        this.announcementsextentDepartmentid = announcementsextentDepartmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_announcementsextent.announcementsExtent_announcementsId
     *
     * @return the value of oas_announcementsextent.announcementsExtent_announcementsId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getAnnouncementsextentAnnouncementsid() {
        return announcementsextentAnnouncementsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_announcementsextent.announcementsExtent_announcementsId
     *
     * @param announcementsextentAnnouncementsid the value for oas_announcementsextent.announcementsExtent_announcementsId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setAnnouncementsextentAnnouncementsid(Integer announcementsextentAnnouncementsid) {
        this.announcementsextentAnnouncementsid = announcementsextentAnnouncementsid;
    }
}