package com.bj186.oas.pojo;

import java.util.Date;

public class Announcements {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_announcements.announcements_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer announcementsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_announcements.announcements_date
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Date announcementsDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_announcements.announcements_notifier
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String announcementsNotifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_announcements.announcements_content
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String announcementsContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_announcements.announcements_notifierId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer announcementsNotifierid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_announcements.announcements_topic
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String announcementsTopic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_announcements.announcements_state
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer announcementsState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_announcements.announcements_id
     *
     * @return the value of oas_announcements.announcements_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getAnnouncementsId() {
        return announcementsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_announcements.announcements_id
     *
     * @param announcementsId the value for oas_announcements.announcements_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setAnnouncementsId(Integer announcementsId) {
        this.announcementsId = announcementsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_announcements.announcements_date
     *
     * @return the value of oas_announcements.announcements_date
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Date getAnnouncementsDate() {
        return announcementsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_announcements.announcements_date
     *
     * @param announcementsDate the value for oas_announcements.announcements_date
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setAnnouncementsDate(Date announcementsDate) {
        this.announcementsDate = announcementsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_announcements.announcements_notifier
     *
     * @return the value of oas_announcements.announcements_notifier
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getAnnouncementsNotifier() {
        return announcementsNotifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_announcements.announcements_notifier
     *
     * @param announcementsNotifier the value for oas_announcements.announcements_notifier
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setAnnouncementsNotifier(String announcementsNotifier) {
        this.announcementsNotifier = announcementsNotifier == null ? null : announcementsNotifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_announcements.announcements_content
     *
     * @return the value of oas_announcements.announcements_content
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getAnnouncementsContent() {
        return announcementsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_announcements.announcements_content
     *
     * @param announcementsContent the value for oas_announcements.announcements_content
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setAnnouncementsContent(String announcementsContent) {
        this.announcementsContent = announcementsContent == null ? null : announcementsContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_announcements.announcements_notifierId
     *
     * @return the value of oas_announcements.announcements_notifierId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getAnnouncementsNotifierid() {
        return announcementsNotifierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_announcements.announcements_notifierId
     *
     * @param announcementsNotifierid the value for oas_announcements.announcements_notifierId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setAnnouncementsNotifierid(Integer announcementsNotifierid) {
        this.announcementsNotifierid = announcementsNotifierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_announcements.announcements_topic
     *
     * @return the value of oas_announcements.announcements_topic
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getAnnouncementsTopic() {
        return announcementsTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_announcements.announcements_topic
     *
     * @param announcementsTopic the value for oas_announcements.announcements_topic
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setAnnouncementsTopic(String announcementsTopic) {
        this.announcementsTopic = announcementsTopic == null ? null : announcementsTopic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_announcements.announcements_state
     *
     * @return the value of oas_announcements.announcements_state
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getAnnouncementsState() {
        return announcementsState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_announcements.announcements_state
     *
     * @param announcementsState the value for oas_announcements.announcements_state
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setAnnouncementsState(Integer announcementsState) {
        this.announcementsState = announcementsState;
    }
}