package com.bj186.oas.pojo;

import java.util.Date;

public class Calendar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_calendar.calendar_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String calendarId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_calendar.calendar_stff_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer calendarStffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_calendar.calendar_type
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String calendarType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_calendar.calendar_startTime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Date calendarStarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_calendar.calendar_sendTime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Date calendarSendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_calendar.calendar_adjunctUrl
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String calendarAdjuncturl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_calendar.calerdar_createTime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Date calerdarCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_calendar.calendar_content
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String calendarContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_calendar.calendar_id
     *
     * @return the value of oas_calendar.calendar_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getCalendarId() {
        return calendarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_calendar.calendar_id
     *
     * @param calendarId the value for oas_calendar.calendar_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setCalendarId(String calendarId) {
        this.calendarId = calendarId == null ? null : calendarId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_calendar.calendar_stff_id
     *
     * @return the value of oas_calendar.calendar_stff_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getCalendarStffId() {
        return calendarStffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_calendar.calendar_stff_id
     *
     * @param calendarStffId the value for oas_calendar.calendar_stff_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setCalendarStffId(Integer calendarStffId) {
        this.calendarStffId = calendarStffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_calendar.calendar_type
     *
     * @return the value of oas_calendar.calendar_type
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getCalendarType() {
        return calendarType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_calendar.calendar_type
     *
     * @param calendarType the value for oas_calendar.calendar_type
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setCalendarType(String calendarType) {
        this.calendarType = calendarType == null ? null : calendarType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_calendar.calendar_startTime
     *
     * @return the value of oas_calendar.calendar_startTime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Date getCalendarStarttime() {
        return calendarStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_calendar.calendar_startTime
     *
     * @param calendarStarttime the value for oas_calendar.calendar_startTime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setCalendarStarttime(Date calendarStarttime) {
        this.calendarStarttime = calendarStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_calendar.calendar_sendTime
     *
     * @return the value of oas_calendar.calendar_sendTime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Date getCalendarSendtime() {
        return calendarSendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_calendar.calendar_sendTime
     *
     * @param calendarSendtime the value for oas_calendar.calendar_sendTime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setCalendarSendtime(Date calendarSendtime) {
        this.calendarSendtime = calendarSendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_calendar.calendar_adjunctUrl
     *
     * @return the value of oas_calendar.calendar_adjunctUrl
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getCalendarAdjuncturl() {
        return calendarAdjuncturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_calendar.calendar_adjunctUrl
     *
     * @param calendarAdjuncturl the value for oas_calendar.calendar_adjunctUrl
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setCalendarAdjuncturl(String calendarAdjuncturl) {
        this.calendarAdjuncturl = calendarAdjuncturl == null ? null : calendarAdjuncturl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_calendar.calerdar_createTime
     *
     * @return the value of oas_calendar.calerdar_createTime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Date getCalerdarCreatetime() {
        return calerdarCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_calendar.calerdar_createTime
     *
     * @param calerdarCreatetime the value for oas_calendar.calerdar_createTime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setCalerdarCreatetime(Date calerdarCreatetime) {
        this.calerdarCreatetime = calerdarCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_calendar.calendar_content
     *
     * @return the value of oas_calendar.calendar_content
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getCalendarContent() {
        return calendarContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_calendar.calendar_content
     *
     * @param calendarContent the value for oas_calendar.calendar_content
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setCalendarContent(String calendarContent) {
        this.calendarContent = calendarContent == null ? null : calendarContent.trim();
    }
}