package com.bj186.oas.pojo;

import java.util.Date;

public class CheckingIn {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_checkingin.checkingin_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String checkinginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_checkingin.check_stff_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer checkStffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_checkingin.checkingin_startTime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Date checkinginStarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_checkingin.checkingin_sendTime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Date checkinginSendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_checkingin.checkingin_state
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String checkinginState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_checkingin.checkingin_id
     *
     * @return the value of oas_checkingin.checkingin_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getCheckinginId() {
        return checkinginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_checkingin.checkingin_id
     *
     * @param checkinginId the value for oas_checkingin.checkingin_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setCheckinginId(String checkinginId) {
        this.checkinginId = checkinginId == null ? null : checkinginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_checkingin.check_stff_id
     *
     * @return the value of oas_checkingin.check_stff_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getCheckStffId() {
        return checkStffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_checkingin.check_stff_id
     *
     * @param checkStffId the value for oas_checkingin.check_stff_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setCheckStffId(Integer checkStffId) {
        this.checkStffId = checkStffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_checkingin.checkingin_startTime
     *
     * @return the value of oas_checkingin.checkingin_startTime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Date getCheckinginStarttime() {
        return checkinginStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_checkingin.checkingin_startTime
     *
     * @param checkinginStarttime the value for oas_checkingin.checkingin_startTime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setCheckinginStarttime(Date checkinginStarttime) {
        this.checkinginStarttime = checkinginStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_checkingin.checkingin_sendTime
     *
     * @return the value of oas_checkingin.checkingin_sendTime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Date getCheckinginSendtime() {
        return checkinginSendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_checkingin.checkingin_sendTime
     *
     * @param checkinginSendtime the value for oas_checkingin.checkingin_sendTime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setCheckinginSendtime(Date checkinginSendtime) {
        this.checkinginSendtime = checkinginSendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_checkingin.checkingin_state
     *
     * @return the value of oas_checkingin.checkingin_state
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getCheckinginState() {
        return checkinginState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_checkingin.checkingin_state
     *
     * @param checkinginState the value for oas_checkingin.checkingin_state
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setCheckinginState(String checkinginState) {
        this.checkinginState = checkinginState == null ? null : checkinginState.trim();
    }
}