package com.bj186.oas.pojo;

import java.util.Date;

public class Contract {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_contract.contract_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_contract.contract_firstParty
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String contractFirstparty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_contract.contract_secondParty
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String contractSecondparty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_contract.contract_secondPartyId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer contractSecondpartyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_contract.contract_entryDate
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Date contractEntrydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_contract.contract_signDate
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Date contractSigndate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_contract.contract_salaryId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer contractSalaryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_contract.contract_content
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String contractContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_contract.contract_id
     *
     * @return the value of oas_contract.contract_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_contract.contract_id
     *
     * @param contractId the value for oas_contract.contract_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setContractId(String contractId) {
        this.contractId = contractId == null ? null : contractId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_contract.contract_firstParty
     *
     * @return the value of oas_contract.contract_firstParty
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getContractFirstparty() {
        return contractFirstparty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_contract.contract_firstParty
     *
     * @param contractFirstparty the value for oas_contract.contract_firstParty
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setContractFirstparty(String contractFirstparty) {
        this.contractFirstparty = contractFirstparty == null ? null : contractFirstparty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_contract.contract_secondParty
     *
     * @return the value of oas_contract.contract_secondParty
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getContractSecondparty() {
        return contractSecondparty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_contract.contract_secondParty
     *
     * @param contractSecondparty the value for oas_contract.contract_secondParty
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setContractSecondparty(String contractSecondparty) {
        this.contractSecondparty = contractSecondparty == null ? null : contractSecondparty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_contract.contract_secondPartyId
     *
     * @return the value of oas_contract.contract_secondPartyId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getContractSecondpartyid() {
        return contractSecondpartyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_contract.contract_secondPartyId
     *
     * @param contractSecondpartyid the value for oas_contract.contract_secondPartyId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setContractSecondpartyid(Integer contractSecondpartyid) {
        this.contractSecondpartyid = contractSecondpartyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_contract.contract_entryDate
     *
     * @return the value of oas_contract.contract_entryDate
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Date getContractEntrydate() {
        return contractEntrydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_contract.contract_entryDate
     *
     * @param contractEntrydate the value for oas_contract.contract_entryDate
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setContractEntrydate(Date contractEntrydate) {
        this.contractEntrydate = contractEntrydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_contract.contract_signDate
     *
     * @return the value of oas_contract.contract_signDate
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Date getContractSigndate() {
        return contractSigndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_contract.contract_signDate
     *
     * @param contractSigndate the value for oas_contract.contract_signDate
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setContractSigndate(Date contractSigndate) {
        this.contractSigndate = contractSigndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_contract.contract_salaryId
     *
     * @return the value of oas_contract.contract_salaryId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getContractSalaryid() {
        return contractSalaryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_contract.contract_salaryId
     *
     * @param contractSalaryid the value for oas_contract.contract_salaryId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setContractSalaryid(Integer contractSalaryid) {
        this.contractSalaryid = contractSalaryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_contract.contract_content
     *
     * @return the value of oas_contract.contract_content
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getContractContent() {
        return contractContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_contract.contract_content
     *
     * @param contractContent the value for oas_contract.contract_content
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setContractContent(String contractContent) {
        this.contractContent = contractContent == null ? null : contractContent.trim();
    }
}