package com.bj186.oas.pojo;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_department.dep_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer depId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_department.dep_name
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String depName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_department.dep_managerid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer depManagerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_department.dep_number
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer depNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_department.dep_describe
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String depDescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_department.dep_id
     *
     * @return the value of oas_department.dep_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_department.dep_id
     *
     * @param depId the value for oas_department.dep_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setDepId(Integer depId) {
        this.depId = depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_department.dep_name
     *
     * @return the value of oas_department.dep_name
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getDepName() {
        return depName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_department.dep_name
     *
     * @param depName the value for oas_department.dep_name
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setDepName(String depName) {
        this.depName = depName == null ? null : depName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_department.dep_managerid
     *
     * @return the value of oas_department.dep_managerid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getDepManagerid() {
        return depManagerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_department.dep_managerid
     *
     * @param depManagerid the value for oas_department.dep_managerid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setDepManagerid(Integer depManagerid) {
        this.depManagerid = depManagerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_department.dep_number
     *
     * @return the value of oas_department.dep_number
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getDepNumber() {
        return depNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_department.dep_number
     *
     * @param depNumber the value for oas_department.dep_number
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setDepNumber(Integer depNumber) {
        this.depNumber = depNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_department.dep_describe
     *
     * @return the value of oas_department.dep_describe
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getDepDescribe() {
        return depDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_department.dep_describe
     *
     * @param depDescribe the value for oas_department.dep_describe
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setDepDescribe(String depDescribe) {
        this.depDescribe = depDescribe == null ? null : depDescribe.trim();
    }
}