package com.bj186.oas.pojo;

import java.util.Date;

public class Files {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_files.files_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer filesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_files.files_staffId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer filesStaffid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_files.files_enterDate
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Date filesEnterdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_files.files_removeDate
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Date filesRemovedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_files.files_contractId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer filesContractid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_files.files_position
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String filesPosition;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_files.files_id
     *
     * @return the value of oas_files.files_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getFilesId() {
        return filesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_files.files_id
     *
     * @param filesId the value for oas_files.files_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setFilesId(Integer filesId) {
        this.filesId = filesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_files.files_staffId
     *
     * @return the value of oas_files.files_staffId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getFilesStaffid() {
        return filesStaffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_files.files_staffId
     *
     * @param filesStaffid the value for oas_files.files_staffId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setFilesStaffid(Integer filesStaffid) {
        this.filesStaffid = filesStaffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_files.files_enterDate
     *
     * @return the value of oas_files.files_enterDate
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Date getFilesEnterdate() {
        return filesEnterdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_files.files_enterDate
     *
     * @param filesEnterdate the value for oas_files.files_enterDate
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setFilesEnterdate(Date filesEnterdate) {
        this.filesEnterdate = filesEnterdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_files.files_removeDate
     *
     * @return the value of oas_files.files_removeDate
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Date getFilesRemovedate() {
        return filesRemovedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_files.files_removeDate
     *
     * @param filesRemovedate the value for oas_files.files_removeDate
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setFilesRemovedate(Date filesRemovedate) {
        this.filesRemovedate = filesRemovedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_files.files_contractId
     *
     * @return the value of oas_files.files_contractId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getFilesContractid() {
        return filesContractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_files.files_contractId
     *
     * @param filesContractid the value for oas_files.files_contractId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setFilesContractid(Integer filesContractid) {
        this.filesContractid = filesContractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_files.files_position
     *
     * @return the value of oas_files.files_position
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getFilesPosition() {
        return filesPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_files.files_position
     *
     * @param filesPosition the value for oas_files.files_position
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setFilesPosition(String filesPosition) {
        this.filesPosition = filesPosition == null ? null : filesPosition.trim();
    }
}