package com.bj186.oas.pojo;

import java.math.BigDecimal;

public class Fixed {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_fixed.fix_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer fixId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_fixed.fixe_name
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String fixeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_fixed.fix_unit
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer fixUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_fixed.fix_number
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer fixNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_fixed.fix_ amount
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private BigDecimal fixAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_fixed.fix_remarks
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String fixRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_fixed.fix_id
     *
     * @return the value of oas_fixed.fix_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getFixId() {
        return fixId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_fixed.fix_id
     *
     * @param fixId the value for oas_fixed.fix_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setFixId(Integer fixId) {
        this.fixId = fixId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_fixed.fixe_name
     *
     * @return the value of oas_fixed.fixe_name
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getFixeName() {
        return fixeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_fixed.fixe_name
     *
     * @param fixeName the value for oas_fixed.fixe_name
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setFixeName(String fixeName) {
        this.fixeName = fixeName == null ? null : fixeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_fixed.fix_unit
     *
     * @return the value of oas_fixed.fix_unit
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getFixUnit() {
        return fixUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_fixed.fix_unit
     *
     * @param fixUnit the value for oas_fixed.fix_unit
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setFixUnit(Integer fixUnit) {
        this.fixUnit = fixUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_fixed.fix_number
     *
     * @return the value of oas_fixed.fix_number
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getFixNumber() {
        return fixNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_fixed.fix_number
     *
     * @param fixNumber the value for oas_fixed.fix_number
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setFixNumber(Integer fixNumber) {
        this.fixNumber = fixNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_fixed.fix_ amount
     *
     * @return the value of oas_fixed.fix_ amount
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public BigDecimal getFixAmount() {
        return fixAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_fixed.fix_ amount
     *
     * @param fixAmount the value for oas_fixed.fix_ amount
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setFixAmount(BigDecimal fixAmount) {
        this.fixAmount = fixAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_fixed.fix_remarks
     *
     * @return the value of oas_fixed.fix_remarks
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getFixRemarks() {
        return fixRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_fixed.fix_remarks
     *
     * @param fixRemarks the value for oas_fixed.fix_remarks
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setFixRemarks(String fixRemarks) {
        this.fixRemarks = fixRemarks == null ? null : fixRemarks.trim();
    }
}