package com.bj186.oas.pojo;

public class LeaveAdvice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_leaveadvice.leaveAdvice_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String leaveadviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_leaveadvice.advicelid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String advicelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_leaveadvice.advicePart
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String advicepart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_leaveadvice.adviceSum
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String advicesum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_leaveadvice.adviceGroup
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String advicegroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_leaveadvice.adviceGroupState
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String advicegroupstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_leaveadvice.advicePartState
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String advicepartstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_leaveadvice.adviceSumState
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String advicesumstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_leaveadvice.leaveAdvice_id
     *
     * @return the value of oas_leaveadvice.leaveAdvice_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getLeaveadviceId() {
        return leaveadviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_leaveadvice.leaveAdvice_id
     *
     * @param leaveadviceId the value for oas_leaveadvice.leaveAdvice_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setLeaveadviceId(String leaveadviceId) {
        this.leaveadviceId = leaveadviceId == null ? null : leaveadviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_leaveadvice.advicelid
     *
     * @return the value of oas_leaveadvice.advicelid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getAdvicelid() {
        return advicelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_leaveadvice.advicelid
     *
     * @param advicelid the value for oas_leaveadvice.advicelid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setAdvicelid(String advicelid) {
        this.advicelid = advicelid == null ? null : advicelid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_leaveadvice.advicePart
     *
     * @return the value of oas_leaveadvice.advicePart
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getAdvicepart() {
        return advicepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_leaveadvice.advicePart
     *
     * @param advicepart the value for oas_leaveadvice.advicePart
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setAdvicepart(String advicepart) {
        this.advicepart = advicepart == null ? null : advicepart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_leaveadvice.adviceSum
     *
     * @return the value of oas_leaveadvice.adviceSum
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getAdvicesum() {
        return advicesum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_leaveadvice.adviceSum
     *
     * @param advicesum the value for oas_leaveadvice.adviceSum
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setAdvicesum(String advicesum) {
        this.advicesum = advicesum == null ? null : advicesum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_leaveadvice.adviceGroup
     *
     * @return the value of oas_leaveadvice.adviceGroup
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getAdvicegroup() {
        return advicegroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_leaveadvice.adviceGroup
     *
     * @param advicegroup the value for oas_leaveadvice.adviceGroup
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setAdvicegroup(String advicegroup) {
        this.advicegroup = advicegroup == null ? null : advicegroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_leaveadvice.adviceGroupState
     *
     * @return the value of oas_leaveadvice.adviceGroupState
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getAdvicegroupstate() {
        return advicegroupstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_leaveadvice.adviceGroupState
     *
     * @param advicegroupstate the value for oas_leaveadvice.adviceGroupState
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setAdvicegroupstate(String advicegroupstate) {
        this.advicegroupstate = advicegroupstate == null ? null : advicegroupstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_leaveadvice.advicePartState
     *
     * @return the value of oas_leaveadvice.advicePartState
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getAdvicepartstate() {
        return advicepartstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_leaveadvice.advicePartState
     *
     * @param advicepartstate the value for oas_leaveadvice.advicePartState
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setAdvicepartstate(String advicepartstate) {
        this.advicepartstate = advicepartstate == null ? null : advicepartstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_leaveadvice.adviceSumState
     *
     * @return the value of oas_leaveadvice.adviceSumState
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getAdvicesumstate() {
        return advicesumstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_leaveadvice.adviceSumState
     *
     * @param advicesumstate the value for oas_leaveadvice.adviceSumState
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setAdvicesumstate(String advicesumstate) {
        this.advicesumstate = advicesumstate == null ? null : advicesumstate.trim();
    }
}