package com.bj186.oas.pojo;

import java.util.Date;

public class Leave {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_leave.leave_Id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String leaveId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_leave.leave_staff_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer leaveStaffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_leave.leave_processing
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String leaveProcessing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_leave.leave_title
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String leaveTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_leave.leave_type
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String leaveType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_leave.leave_time
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer leaveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_leave.leave_startTime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Date leaveStarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_leave.leave_sendTime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Date leaveSendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_leave.leave_state
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String leaveState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_leave.leave_reason
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String leaveReason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_leave.leave_Id
     *
     * @return the value of oas_leave.leave_Id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getLeaveId() {
        return leaveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_leave.leave_Id
     *
     * @param leaveId the value for oas_leave.leave_Id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setLeaveId(String leaveId) {
        this.leaveId = leaveId == null ? null : leaveId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_leave.leave_staff_id
     *
     * @return the value of oas_leave.leave_staff_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getLeaveStaffId() {
        return leaveStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_leave.leave_staff_id
     *
     * @param leaveStaffId the value for oas_leave.leave_staff_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setLeaveStaffId(Integer leaveStaffId) {
        this.leaveStaffId = leaveStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_leave.leave_processing
     *
     * @return the value of oas_leave.leave_processing
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getLeaveProcessing() {
        return leaveProcessing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_leave.leave_processing
     *
     * @param leaveProcessing the value for oas_leave.leave_processing
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setLeaveProcessing(String leaveProcessing) {
        this.leaveProcessing = leaveProcessing == null ? null : leaveProcessing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_leave.leave_title
     *
     * @return the value of oas_leave.leave_title
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getLeaveTitle() {
        return leaveTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_leave.leave_title
     *
     * @param leaveTitle the value for oas_leave.leave_title
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setLeaveTitle(String leaveTitle) {
        this.leaveTitle = leaveTitle == null ? null : leaveTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_leave.leave_type
     *
     * @return the value of oas_leave.leave_type
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getLeaveType() {
        return leaveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_leave.leave_type
     *
     * @param leaveType the value for oas_leave.leave_type
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setLeaveType(String leaveType) {
        this.leaveType = leaveType == null ? null : leaveType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_leave.leave_time
     *
     * @return the value of oas_leave.leave_time
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getLeaveTime() {
        return leaveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_leave.leave_time
     *
     * @param leaveTime the value for oas_leave.leave_time
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setLeaveTime(Integer leaveTime) {
        this.leaveTime = leaveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_leave.leave_startTime
     *
     * @return the value of oas_leave.leave_startTime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Date getLeaveStarttime() {
        return leaveStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_leave.leave_startTime
     *
     * @param leaveStarttime the value for oas_leave.leave_startTime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setLeaveStarttime(Date leaveStarttime) {
        this.leaveStarttime = leaveStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_leave.leave_sendTime
     *
     * @return the value of oas_leave.leave_sendTime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Date getLeaveSendtime() {
        return leaveSendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_leave.leave_sendTime
     *
     * @param leaveSendtime the value for oas_leave.leave_sendTime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setLeaveSendtime(Date leaveSendtime) {
        this.leaveSendtime = leaveSendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_leave.leave_state
     *
     * @return the value of oas_leave.leave_state
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getLeaveState() {
        return leaveState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_leave.leave_state
     *
     * @param leaveState the value for oas_leave.leave_state
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setLeaveState(String leaveState) {
        this.leaveState = leaveState == null ? null : leaveState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_leave.leave_reason
     *
     * @return the value of oas_leave.leave_reason
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getLeaveReason() {
        return leaveReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_leave.leave_reason
     *
     * @param leaveReason the value for oas_leave.leave_reason
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setLeaveReason(String leaveReason) {
        this.leaveReason = leaveReason == null ? null : leaveReason.trim();
    }
}