package com.bj186.oas.pojo;

public class MeetingStaff {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_meetingstaff.meetingStaff_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String meetingstaffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_meetingstaff.meetingStaff_meeting_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String meetingstaffMeetingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_meetingstaff.meetingStaff_empid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer meetingstaffEmpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_meetingstaff.meetingStaff_stffId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer meetingstaffStffid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_meetingstaff.meetingStaff_id
     *
     * @return the value of oas_meetingstaff.meetingStaff_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getMeetingstaffId() {
        return meetingstaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_meetingstaff.meetingStaff_id
     *
     * @param meetingstaffId the value for oas_meetingstaff.meetingStaff_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setMeetingstaffId(String meetingstaffId) {
        this.meetingstaffId = meetingstaffId == null ? null : meetingstaffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_meetingstaff.meetingStaff_meeting_id
     *
     * @return the value of oas_meetingstaff.meetingStaff_meeting_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getMeetingstaffMeetingId() {
        return meetingstaffMeetingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_meetingstaff.meetingStaff_meeting_id
     *
     * @param meetingstaffMeetingId the value for oas_meetingstaff.meetingStaff_meeting_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setMeetingstaffMeetingId(String meetingstaffMeetingId) {
        this.meetingstaffMeetingId = meetingstaffMeetingId == null ? null : meetingstaffMeetingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_meetingstaff.meetingStaff_empid
     *
     * @return the value of oas_meetingstaff.meetingStaff_empid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getMeetingstaffEmpid() {
        return meetingstaffEmpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_meetingstaff.meetingStaff_empid
     *
     * @param meetingstaffEmpid the value for oas_meetingstaff.meetingStaff_empid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setMeetingstaffEmpid(Integer meetingstaffEmpid) {
        this.meetingstaffEmpid = meetingstaffEmpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_meetingstaff.meetingStaff_stffId
     *
     * @return the value of oas_meetingstaff.meetingStaff_stffId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getMeetingstaffStffid() {
        return meetingstaffStffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_meetingstaff.meetingStaff_stffId
     *
     * @param meetingstaffStffid the value for oas_meetingstaff.meetingStaff_stffId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setMeetingstaffStffid(Integer meetingstaffStffid) {
        this.meetingstaffStffid = meetingstaffStffid;
    }
}