package com.bj186.oas.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Pay {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_pay.pay_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer payId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_pay.pay_staffid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer payStaffid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_pay.pay_depid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer payDepid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_pay.pay_date
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Date payDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_pay.pay_accum
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private BigDecimal payAccum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_pay.pay_wage
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private BigDecimal payWage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_pay.pay_medical
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private BigDecimal payMedical;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_pay.pay_award
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private BigDecimal payAward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_pay.pay_salary
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private BigDecimal paySalary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_pay.pay_id
     *
     * @return the value of oas_pay.pay_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_pay.pay_id
     *
     * @param payId the value for oas_pay.pay_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setPayId(Integer payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_pay.pay_staffid
     *
     * @return the value of oas_pay.pay_staffid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getPayStaffid() {
        return payStaffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_pay.pay_staffid
     *
     * @param payStaffid the value for oas_pay.pay_staffid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setPayStaffid(Integer payStaffid) {
        this.payStaffid = payStaffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_pay.pay_depid
     *
     * @return the value of oas_pay.pay_depid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getPayDepid() {
        return payDepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_pay.pay_depid
     *
     * @param payDepid the value for oas_pay.pay_depid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setPayDepid(Integer payDepid) {
        this.payDepid = payDepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_pay.pay_date
     *
     * @return the value of oas_pay.pay_date
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Date getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_pay.pay_date
     *
     * @param payDate the value for oas_pay.pay_date
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_pay.pay_accum
     *
     * @return the value of oas_pay.pay_accum
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public BigDecimal getPayAccum() {
        return payAccum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_pay.pay_accum
     *
     * @param payAccum the value for oas_pay.pay_accum
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setPayAccum(BigDecimal payAccum) {
        this.payAccum = payAccum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_pay.pay_wage
     *
     * @return the value of oas_pay.pay_wage
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public BigDecimal getPayWage() {
        return payWage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_pay.pay_wage
     *
     * @param payWage the value for oas_pay.pay_wage
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setPayWage(BigDecimal payWage) {
        this.payWage = payWage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_pay.pay_medical
     *
     * @return the value of oas_pay.pay_medical
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public BigDecimal getPayMedical() {
        return payMedical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_pay.pay_medical
     *
     * @param payMedical the value for oas_pay.pay_medical
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setPayMedical(BigDecimal payMedical) {
        this.payMedical = payMedical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_pay.pay_award
     *
     * @return the value of oas_pay.pay_award
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public BigDecimal getPayAward() {
        return payAward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_pay.pay_award
     *
     * @param payAward the value for oas_pay.pay_award
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setPayAward(BigDecimal payAward) {
        this.payAward = payAward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_pay.pay_salary
     *
     * @return the value of oas_pay.pay_salary
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public BigDecimal getPaySalary() {
        return paySalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_pay.pay_salary
     *
     * @param paySalary the value for oas_pay.pay_salary
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setPaySalary(BigDecimal paySalary) {
        this.paySalary = paySalary;
    }
}