package com.bj186.oas.pojo;

public class Position {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_position.position_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer positionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_position.position_name
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String positionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_position.position_describe
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String positionDescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_position.position_id
     *
     * @return the value of oas_position.position_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_position.position_id
     *
     * @param positionId the value for oas_position.position_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_position.position_name
     *
     * @return the value of oas_position.position_name
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_position.position_name
     *
     * @param positionName the value for oas_position.position_name
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName == null ? null : positionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_position.position_describe
     *
     * @return the value of oas_position.position_describe
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getPositionDescribe() {
        return positionDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_position.position_describe
     *
     * @param positionDescribe the value for oas_position.position_describe
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setPositionDescribe(String positionDescribe) {
        this.positionDescribe = positionDescribe == null ? null : positionDescribe.trim();
    }
}