package com.bj186.oas.pojo;

public class Power {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_power.power_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer powerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_power.power_name
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String powerName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_power.power_id
     *
     * @return the value of oas_power.power_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getPowerId() {
        return powerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_power.power_id
     *
     * @param powerId the value for oas_power.power_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setPowerId(Integer powerId) {
        this.powerId = powerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_power.power_name
     *
     * @return the value of oas_power.power_name
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getPowerName() {
        return powerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_power.power_name
     *
     * @param powerName the value for oas_power.power_name
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setPowerName(String powerName) {
        this.powerName = powerName == null ? null : powerName.trim();
    }
}