package com.bj186.oas.pojo;

public class Proof {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_proof.proof_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer proofId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_proof.proof_staffid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer proofStaffid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_proof.proof_depid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer proofDepid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_proof.proof_document
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String proofDocument;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_proof.proof_condition
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer proofCondition;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_proof.proof_id
     *
     * @return the value of oas_proof.proof_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getProofId() {
        return proofId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_proof.proof_id
     *
     * @param proofId the value for oas_proof.proof_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setProofId(Integer proofId) {
        this.proofId = proofId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_proof.proof_staffid
     *
     * @return the value of oas_proof.proof_staffid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getProofStaffid() {
        return proofStaffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_proof.proof_staffid
     *
     * @param proofStaffid the value for oas_proof.proof_staffid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setProofStaffid(Integer proofStaffid) {
        this.proofStaffid = proofStaffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_proof.proof_depid
     *
     * @return the value of oas_proof.proof_depid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getProofDepid() {
        return proofDepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_proof.proof_depid
     *
     * @param proofDepid the value for oas_proof.proof_depid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setProofDepid(Integer proofDepid) {
        this.proofDepid = proofDepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_proof.proof_document
     *
     * @return the value of oas_proof.proof_document
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getProofDocument() {
        return proofDocument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_proof.proof_document
     *
     * @param proofDocument the value for oas_proof.proof_document
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setProofDocument(String proofDocument) {
        this.proofDocument = proofDocument == null ? null : proofDocument.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_proof.proof_condition
     *
     * @return the value of oas_proof.proof_condition
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getProofCondition() {
        return proofCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_proof.proof_condition
     *
     * @param proofCondition the value for oas_proof.proof_condition
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setProofCondition(Integer proofCondition) {
        this.proofCondition = proofCondition;
    }
}