package com.bj186.oas.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Reimburse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_reimburse.reim_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer reimId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_reimburse.reim_staffid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer reimStaffid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_reimburse.reim_depid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer reimDepid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_reimburse.reim_matter
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String reimMatter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_reimburse.reim_starttime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Date reimStarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_reimburse.reim_endtime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Date reimEndtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_reimburse.reim_place
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String reimPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_reimburse.reim_traffic
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private BigDecimal reimTraffic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_reimburse.reim_stay
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private BigDecimal reimStay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_reimburse.reim_referr
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private BigDecimal reimReferr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_reimburse.reim_id
     *
     * @return the value of oas_reimburse.reim_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getReimId() {
        return reimId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_reimburse.reim_id
     *
     * @param reimId the value for oas_reimburse.reim_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setReimId(Integer reimId) {
        this.reimId = reimId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_reimburse.reim_staffid
     *
     * @return the value of oas_reimburse.reim_staffid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getReimStaffid() {
        return reimStaffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_reimburse.reim_staffid
     *
     * @param reimStaffid the value for oas_reimburse.reim_staffid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setReimStaffid(Integer reimStaffid) {
        this.reimStaffid = reimStaffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_reimburse.reim_depid
     *
     * @return the value of oas_reimburse.reim_depid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getReimDepid() {
        return reimDepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_reimburse.reim_depid
     *
     * @param reimDepid the value for oas_reimburse.reim_depid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setReimDepid(Integer reimDepid) {
        this.reimDepid = reimDepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_reimburse.reim_matter
     *
     * @return the value of oas_reimburse.reim_matter
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getReimMatter() {
        return reimMatter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_reimburse.reim_matter
     *
     * @param reimMatter the value for oas_reimburse.reim_matter
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setReimMatter(String reimMatter) {
        this.reimMatter = reimMatter == null ? null : reimMatter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_reimburse.reim_starttime
     *
     * @return the value of oas_reimburse.reim_starttime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Date getReimStarttime() {
        return reimStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_reimburse.reim_starttime
     *
     * @param reimStarttime the value for oas_reimburse.reim_starttime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setReimStarttime(Date reimStarttime) {
        this.reimStarttime = reimStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_reimburse.reim_endtime
     *
     * @return the value of oas_reimburse.reim_endtime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Date getReimEndtime() {
        return reimEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_reimburse.reim_endtime
     *
     * @param reimEndtime the value for oas_reimburse.reim_endtime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setReimEndtime(Date reimEndtime) {
        this.reimEndtime = reimEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_reimburse.reim_place
     *
     * @return the value of oas_reimburse.reim_place
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getReimPlace() {
        return reimPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_reimburse.reim_place
     *
     * @param reimPlace the value for oas_reimburse.reim_place
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setReimPlace(String reimPlace) {
        this.reimPlace = reimPlace == null ? null : reimPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_reimburse.reim_traffic
     *
     * @return the value of oas_reimburse.reim_traffic
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public BigDecimal getReimTraffic() {
        return reimTraffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_reimburse.reim_traffic
     *
     * @param reimTraffic the value for oas_reimburse.reim_traffic
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setReimTraffic(BigDecimal reimTraffic) {
        this.reimTraffic = reimTraffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_reimburse.reim_stay
     *
     * @return the value of oas_reimburse.reim_stay
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public BigDecimal getReimStay() {
        return reimStay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_reimburse.reim_stay
     *
     * @param reimStay the value for oas_reimburse.reim_stay
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setReimStay(BigDecimal reimStay) {
        this.reimStay = reimStay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_reimburse.reim_referr
     *
     * @return the value of oas_reimburse.reim_referr
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public BigDecimal getReimReferr() {
        return reimReferr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_reimburse.reim_referr
     *
     * @param reimReferr the value for oas_reimburse.reim_referr
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setReimReferr(BigDecimal reimReferr) {
        this.reimReferr = reimReferr;
    }
}