package com.bj186.oas.pojo;

import java.util.Date;

public class Rent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_rent.rent_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer rentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_rent.rent_fixid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer rentFixid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_rent.rent_number
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer rentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_rent.rent_starttime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Date rentStarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_rent.rent_endtime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Date rentEndtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_rent.rent_cond
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer rentCond;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_rent.rent_id
     *
     * @return the value of oas_rent.rent_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getRentId() {
        return rentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_rent.rent_id
     *
     * @param rentId the value for oas_rent.rent_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setRentId(Integer rentId) {
        this.rentId = rentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_rent.rent_fixid
     *
     * @return the value of oas_rent.rent_fixid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getRentFixid() {
        return rentFixid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_rent.rent_fixid
     *
     * @param rentFixid the value for oas_rent.rent_fixid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setRentFixid(Integer rentFixid) {
        this.rentFixid = rentFixid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_rent.rent_number
     *
     * @return the value of oas_rent.rent_number
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getRentNumber() {
        return rentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_rent.rent_number
     *
     * @param rentNumber the value for oas_rent.rent_number
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setRentNumber(Integer rentNumber) {
        this.rentNumber = rentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_rent.rent_starttime
     *
     * @return the value of oas_rent.rent_starttime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Date getRentStarttime() {
        return rentStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_rent.rent_starttime
     *
     * @param rentStarttime the value for oas_rent.rent_starttime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setRentStarttime(Date rentStarttime) {
        this.rentStarttime = rentStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_rent.rent_endtime
     *
     * @return the value of oas_rent.rent_endtime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Date getRentEndtime() {
        return rentEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_rent.rent_endtime
     *
     * @param rentEndtime the value for oas_rent.rent_endtime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setRentEndtime(Date rentEndtime) {
        this.rentEndtime = rentEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_rent.rent_cond
     *
     * @return the value of oas_rent.rent_cond
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getRentCond() {
        return rentCond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_rent.rent_cond
     *
     * @param rentCond the value for oas_rent.rent_cond
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setRentCond(Integer rentCond) {
        this.rentCond = rentCond;
    }
}