package com.bj186.oas.pojo;

import java.util.Date;

public class Rule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_rule.rule_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer ruleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_rule.rule_departmentId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer ruleDepartmentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_rule.rule_creatorId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer ruleCreatorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_rule.rule_creator
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String ruleCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_rule.rule_releaseDate
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Date ruleReleasedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_rule.rule_title
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String ruleTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_rule.rule_state
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer ruleState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_rule.rule_content
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String ruleContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_rule.rule_id
     *
     * @return the value of oas_rule.rule_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_rule.rule_id
     *
     * @param ruleId the value for oas_rule.rule_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setRuleId(Integer ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_rule.rule_departmentId
     *
     * @return the value of oas_rule.rule_departmentId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getRuleDepartmentid() {
        return ruleDepartmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_rule.rule_departmentId
     *
     * @param ruleDepartmentid the value for oas_rule.rule_departmentId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setRuleDepartmentid(Integer ruleDepartmentid) {
        this.ruleDepartmentid = ruleDepartmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_rule.rule_creatorId
     *
     * @return the value of oas_rule.rule_creatorId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getRuleCreatorid() {
        return ruleCreatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_rule.rule_creatorId
     *
     * @param ruleCreatorid the value for oas_rule.rule_creatorId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setRuleCreatorid(Integer ruleCreatorid) {
        this.ruleCreatorid = ruleCreatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_rule.rule_creator
     *
     * @return the value of oas_rule.rule_creator
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getRuleCreator() {
        return ruleCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_rule.rule_creator
     *
     * @param ruleCreator the value for oas_rule.rule_creator
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setRuleCreator(String ruleCreator) {
        this.ruleCreator = ruleCreator == null ? null : ruleCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_rule.rule_releaseDate
     *
     * @return the value of oas_rule.rule_releaseDate
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Date getRuleReleasedate() {
        return ruleReleasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_rule.rule_releaseDate
     *
     * @param ruleReleasedate the value for oas_rule.rule_releaseDate
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setRuleReleasedate(Date ruleReleasedate) {
        this.ruleReleasedate = ruleReleasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_rule.rule_title
     *
     * @return the value of oas_rule.rule_title
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getRuleTitle() {
        return ruleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_rule.rule_title
     *
     * @param ruleTitle the value for oas_rule.rule_title
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setRuleTitle(String ruleTitle) {
        this.ruleTitle = ruleTitle == null ? null : ruleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_rule.rule_state
     *
     * @return the value of oas_rule.rule_state
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getRuleState() {
        return ruleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_rule.rule_state
     *
     * @param ruleState the value for oas_rule.rule_state
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setRuleState(Integer ruleState) {
        this.ruleState = ruleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_rule.rule_content
     *
     * @return the value of oas_rule.rule_content
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getRuleContent() {
        return ruleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_rule.rule_content
     *
     * @param ruleContent the value for oas_rule.rule_content
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setRuleContent(String ruleContent) {
        this.ruleContent = ruleContent == null ? null : ruleContent.trim();
    }
}