package com.bj186.oas.pojo;

import java.util.Date;

public class Staff {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_staff.staff_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_staff.staff_name
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String staffName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_staff.staff_sex
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String staffSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_staff.staff_age
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Byte staffAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_staff.staff_phone
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String staffPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_staff.staff_idntityCardID
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String staffIdntitycardid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_staff.staff_birthday
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Date staffBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_staff.staff_positionid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer staffPositionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_staff.staff_adress
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String staffAdress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_staff.staff_wage
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String staffWage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_staff.staff_email
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String staffEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_staff.staff_id
     *
     * @return the value of oas_staff.staff_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_staff.staff_id
     *
     * @param staffId the value for oas_staff.staff_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_staff.staff_name
     *
     * @return the value of oas_staff.staff_name
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_staff.staff_name
     *
     * @param staffName the value for oas_staff.staff_name
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName == null ? null : staffName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_staff.staff_sex
     *
     * @return the value of oas_staff.staff_sex
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getStaffSex() {
        return staffSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_staff.staff_sex
     *
     * @param staffSex the value for oas_staff.staff_sex
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setStaffSex(String staffSex) {
        this.staffSex = staffSex == null ? null : staffSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_staff.staff_age
     *
     * @return the value of oas_staff.staff_age
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Byte getStaffAge() {
        return staffAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_staff.staff_age
     *
     * @param staffAge the value for oas_staff.staff_age
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setStaffAge(Byte staffAge) {
        this.staffAge = staffAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_staff.staff_phone
     *
     * @return the value of oas_staff.staff_phone
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getStaffPhone() {
        return staffPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_staff.staff_phone
     *
     * @param staffPhone the value for oas_staff.staff_phone
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setStaffPhone(String staffPhone) {
        this.staffPhone = staffPhone == null ? null : staffPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_staff.staff_idntityCardID
     *
     * @return the value of oas_staff.staff_idntityCardID
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getStaffIdntitycardid() {
        return staffIdntitycardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_staff.staff_idntityCardID
     *
     * @param staffIdntitycardid the value for oas_staff.staff_idntityCardID
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setStaffIdntitycardid(String staffIdntitycardid) {
        this.staffIdntitycardid = staffIdntitycardid == null ? null : staffIdntitycardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_staff.staff_birthday
     *
     * @return the value of oas_staff.staff_birthday
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Date getStaffBirthday() {
        return staffBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_staff.staff_birthday
     *
     * @param staffBirthday the value for oas_staff.staff_birthday
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setStaffBirthday(Date staffBirthday) {
        this.staffBirthday = staffBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_staff.staff_positionid
     *
     * @return the value of oas_staff.staff_positionid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getStaffPositionid() {
        return staffPositionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_staff.staff_positionid
     *
     * @param staffPositionid the value for oas_staff.staff_positionid
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setStaffPositionid(Integer staffPositionid) {
        this.staffPositionid = staffPositionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_staff.staff_adress
     *
     * @return the value of oas_staff.staff_adress
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getStaffAdress() {
        return staffAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_staff.staff_adress
     *
     * @param staffAdress the value for oas_staff.staff_adress
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setStaffAdress(String staffAdress) {
        this.staffAdress = staffAdress == null ? null : staffAdress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_staff.staff_wage
     *
     * @return the value of oas_staff.staff_wage
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getStaffWage() {
        return staffWage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_staff.staff_wage
     *
     * @param staffWage the value for oas_staff.staff_wage
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setStaffWage(String staffWage) {
        this.staffWage = staffWage == null ? null : staffWage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_staff.staff_email
     *
     * @return the value of oas_staff.staff_email
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getStaffEmail() {
        return staffEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_staff.staff_email
     *
     * @param staffEmail the value for oas_staff.staff_email
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setStaffEmail(String staffEmail) {
        this.staffEmail = staffEmail == null ? null : staffEmail.trim();
    }
}