package com.bj186.oas.pojo;

public class StaffPower {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_staffpower.sp_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer spId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_staffpower.sp_staffID
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer spStaffid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_staffpower.sp_powerID
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer spPowerid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_staffpower.sp_id
     *
     * @return the value of oas_staffpower.sp_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getSpId() {
        return spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_staffpower.sp_id
     *
     * @param spId the value for oas_staffpower.sp_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setSpId(Integer spId) {
        this.spId = spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_staffpower.sp_staffID
     *
     * @return the value of oas_staffpower.sp_staffID
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getSpStaffid() {
        return spStaffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_staffpower.sp_staffID
     *
     * @param spStaffid the value for oas_staffpower.sp_staffID
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setSpStaffid(Integer spStaffid) {
        this.spStaffid = spStaffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_staffpower.sp_powerID
     *
     * @return the value of oas_staffpower.sp_powerID
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getSpPowerid() {
        return spPowerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_staffpower.sp_powerID
     *
     * @param spPowerid the value for oas_staffpower.sp_powerID
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setSpPowerid(Integer spPowerid) {
        this.spPowerid = spPowerid;
    }
}