package com.bj186.oas.pojo;

public class StaffDep {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_staffdep.sd_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer sdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_staffdep.sd_staffId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer sdStaffid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_staffdep.sd_depId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer sdDepid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_staffdep.sd_id
     *
     * @return the value of oas_staffdep.sd_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getSdId() {
        return sdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_staffdep.sd_id
     *
     * @param sdId the value for oas_staffdep.sd_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setSdId(Integer sdId) {
        this.sdId = sdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_staffdep.sd_staffId
     *
     * @return the value of oas_staffdep.sd_staffId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getSdStaffid() {
        return sdStaffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_staffdep.sd_staffId
     *
     * @param sdStaffid the value for oas_staffdep.sd_staffId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setSdStaffid(Integer sdStaffid) {
        this.sdStaffid = sdStaffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_staffdep.sd_depId
     *
     * @return the value of oas_staffdep.sd_depId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getSdDepid() {
        return sdDepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_staffdep.sd_depId
     *
     * @param sdDepid the value for oas_staffdep.sd_depId
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setSdDepid(Integer sdDepid) {
        this.sdDepid = sdDepid;
    }
}