package com.bj186.oas.pojo;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_users.users_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer usersId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_users.users_phone
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String usersPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_users.users_password
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String usersPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_users.users_state
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String usersState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_users.users_id
     *
     * @return the value of oas_users.users_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getUsersId() {
        return usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_users.users_id
     *
     * @param usersId the value for oas_users.users_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_users.users_phone
     *
     * @return the value of oas_users.users_phone
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getUsersPhone() {
        return usersPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_users.users_phone
     *
     * @param usersPhone the value for oas_users.users_phone
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setUsersPhone(String usersPhone) {
        this.usersPhone = usersPhone == null ? null : usersPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_users.users_password
     *
     * @return the value of oas_users.users_password
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getUsersPassword() {
        return usersPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_users.users_password
     *
     * @param usersPassword the value for oas_users.users_password
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setUsersPassword(String usersPassword) {
        this.usersPassword = usersPassword == null ? null : usersPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_users.users_state
     *
     * @return the value of oas_users.users_state
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getUsersState() {
        return usersState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_users.users_state
     *
     * @param usersState the value for oas_users.users_state
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setUsersState(String usersState) {
        this.usersState = usersState == null ? null : usersState.trim();
    }
}