package com.bj186.oas.pojo;

import java.util.Date;

public class WorkLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_worklog.worklog_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer worklogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_worklog.worklog_name
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String worklogName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_worklog.worklog_createdate
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Date worklogCreatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_worklog.worklog_updatetime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Date worklogUpdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_worklog.worklog_createID
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private Integer worklogCreateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oas_worklog.worklog_content
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    private String worklogContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_worklog.worklog_id
     *
     * @return the value of oas_worklog.worklog_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getWorklogId() {
        return worklogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_worklog.worklog_id
     *
     * @param worklogId the value for oas_worklog.worklog_id
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setWorklogId(Integer worklogId) {
        this.worklogId = worklogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_worklog.worklog_name
     *
     * @return the value of oas_worklog.worklog_name
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getWorklogName() {
        return worklogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_worklog.worklog_name
     *
     * @param worklogName the value for oas_worklog.worklog_name
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setWorklogName(String worklogName) {
        this.worklogName = worklogName == null ? null : worklogName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_worklog.worklog_createdate
     *
     * @return the value of oas_worklog.worklog_createdate
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Date getWorklogCreatedate() {
        return worklogCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_worklog.worklog_createdate
     *
     * @param worklogCreatedate the value for oas_worklog.worklog_createdate
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setWorklogCreatedate(Date worklogCreatedate) {
        this.worklogCreatedate = worklogCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_worklog.worklog_updatetime
     *
     * @return the value of oas_worklog.worklog_updatetime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Date getWorklogUpdatetime() {
        return worklogUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_worklog.worklog_updatetime
     *
     * @param worklogUpdatetime the value for oas_worklog.worklog_updatetime
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setWorklogUpdatetime(Date worklogUpdatetime) {
        this.worklogUpdatetime = worklogUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_worklog.worklog_createID
     *
     * @return the value of oas_worklog.worklog_createID
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public Integer getWorklogCreateid() {
        return worklogCreateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_worklog.worklog_createID
     *
     * @param worklogCreateid the value for oas_worklog.worklog_createID
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setWorklogCreateid(Integer worklogCreateid) {
        this.worklogCreateid = worklogCreateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oas_worklog.worklog_content
     *
     * @return the value of oas_worklog.worklog_content
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public String getWorklogContent() {
        return worklogContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oas_worklog.worklog_content
     *
     * @param worklogContent the value for oas_worklog.worklog_content
     *
     * @mbg.generated Tue Jun 18 09:59:51 CST 2019
     */
    public void setWorklogContent(String worklogContent) {
        this.worklogContent = worklogContent == null ? null : worklogContent.trim();
    }
}